POST http://localhost:3000/links
Content-Type: application/json

{
    "id":[1,9,4],
    "country": ["world","nations"]
}

###
POST http://localhost:3000/fixtures
Content-Type: application/json

{
    "league": 13,
    "season": 2024,
    "country": ["conmebol"]
}
###
POST http://localhost:3000/standings
Content-Type: application/json

{
    "league": 13,
    "season": 2024,
    "country": ["conmebol"]
}

