POST http://localhost:3000/links
Content-Type: application/json

{
    "id": [],
    "country": ["world",""]
}
### copa america & euro, con los nuevos validates, podemos 
POST http://localhost:3000/fixtures
Content-Type: application/json

{
    "league": [4,9],
    "season": [2024],
    "country": ["nations"]
}
###
POST http://localhost:3000/standings
Content-Type: application/json

{
    "league": [128],
    "season": [2015,2016,2017,2018,2019,2020,2021,2022],
    "country": ["argentina"]
}
