POST http://localhost:3000/links
###
POST http://localhost:3000/fixtures
Content-Type: application/json

{
    "league": 130,
    "season": 2024,
    "country": ["argentina"]
}
###
POST http://localhost:3000/standings
Content-Type: application/json

{
    "league": 128,
    "season": 2024,
    "country": ["argentina"]
}
